server:
  port: 3000

auth:
  hash_salt: "hash_salt"
  signing_key: "signing_key"
  token_ttl: 86400

db:
  host: "localhost"
  port: 5432
  username: "postgres"
  password: "strongpassword"
  database: "postgres"


